with open(r'c:\Users\14066\WorkBuddy\20260503005229\diet-tracker-pwa\app_v2.js', 'a', encoding='utf-8') as f:
    f.write('\n// === 今日视图（三区Tabs）===\n')
    f.write('function renderToday(p){\n')
    f.write('  const day=appData[curDate]||{food:[],supp:[],med:[]};\n')
    f.write('  const tabs=document.createElement("div"); tabs.className="section-tabs";\n')
    f.write('  [{k:"food",i:"🔥",l:"热量/营养"},{k:"supp",i:"💊",l:"营养补充"},{k:"med",i:"💉",l:"药品记录"}].forEach(t=>{\n')
    f.write('    const b=document.createElement("button");\n')
    f.write('    b.className="sec-tab"+(activeSection===t.k?" active":"");\n')
    f.write('    b.innerHTML=t.i+" "+t.l;\n')
    f.write('    b.onclick=()=>{activeSection=t.k;render();};\n')
    f.write('    tabs.appendChild(b);\n')
    f.write('  }); p.appendChild(tabs);\n')
    f.write('  if(activeSection=="food") renderFoodSec(p,day);\n')
    f.write('  if(activeSection=="supp") renderSuppSec(p,day);\n')
    f.write('  if(activeSection=="med")  renderMedSec(p,day);\n')
    f.write('}\n')
print('Part2 OK')
